# words.py
# Centralized word lists for sedot.py

# Kata-kata yang harus dilewati (awalan, akhiran, imbuhan, kata sambung)
SKIP_WORDS = set([
    'di', 'ke', 'dari', 'pada', 'yang', 'untuk', 'dan', 'atau', 'tapi', 'tetapi',
    'dengan', 'oleh', 'karena', 'sehingga', 'agar', 'supaya', 'jika', 'kalau',
    'apabila', 'walau', 'meski', 'walaupun', 'meskipun', 'sementara',
    'sedang', 'ketika', 'saat', 'setelah', 'sebelum', 'hingga', 'sampai',
    'demi', 'lewat', 'melalui', 'via', 'tanpa', 'sejak', 'selama', 'ketika',
    'sambil', 'seraya', 'biar', 'meski', 'meskipun', 'agar', 'supaya',
    'atas', 'bawah', 'depan', 'belakang', 'samping', 'dalam', 'luar',
    'antara', 'sekitar', 'sebelah', 'hadap', 'tepi', 'pinggir', 'ujung',
    'kah', 'lah', 'tah', 'pun', 'nya',
    'se', 'ber', 'ter', 'me', 'pe', 'per', 'mem', 'pen', 'peng', 'men',
    'pem', 'pel', 'ber', 'ter', 'ke', 'di', 'per', 'se', 'meng', 'meny',
    'memper', 'mempert', 'diper', 'terper',
    'kan', 'an', 'i', 'nya', 'ku', 'mu',
    'ini', 'itu', 'sini', 'situ', 'sana', 'kamu', 'aku', 'saya', 'kita',
    'mereka', 'dia', 'beliau', 'anda', 'kalian', 'kami', 'engkau', 'kau',
    'beliau', 'nya',
    'sebuah', 'suatu', 'sang', 'si', 'para', 'kaum', 'segala', 'seluruh',
    'semua', 'setiap', 'masing', 'beberapa', 'sedikit', 'banyak', 'semua',
    'adalah', 'ialah', 'merupakan', 'menjadi', 'bisa', 'dapat', 'mampu',
    'harus', 'wajib', 'perlu', 'hendak', 'akan', 'sedang', 'telah', 'sudah',
    'pernah', 'belum', 'masih', 'baru', 'hanya', 'cuma', 'sekadar', 'hampir',
    'nyaris', 'agak', 'cukup', 'terlalu', 'amat', 'sangat', 'benar', 'sungguh',
    'ada', 'tidak', 'bukan', 'jangan', 'janganlah', 'usah', 'jangan',
    'mohon', 'tolong', 'harap', 'silahkan', 'mari', 'ayo', 'ayolah',
    'wah', 'aduh', 'astaga', 'ya', 'tidak', 'bukan',
    'dalam', 'oleh', 'pada', 'sebagai', 'bagi', 'menurut', 'tentang',
    'mengenai', 'atas', 'bawah', 'depan', 'belakang', 'samping', 'antara',
    'di', 'ke', 'dari', 'demi', 'hingga', 'sampai', 'selama', 'sementara',
    'seraya', 'ketika', 'sewaktu', 'sebelum', 'sesudah', 'setelah', 'sejak',
    'tatkala', 'selagi', 'sedangkan', 'sambil', 'seraya', 'biar', 'meski',
    'walau', 'walaupun', 'meskipun', 'supaya', 'agar', 'untuk', 'guna',
    'dengan', 'tanpa', 'via', 'lewat', 'melalui', 'oleh', 'sebab', 'karena',
    'lantas', 'lalu', 'kemudian', 'maka', 'oleh_karena', 'sehingga',
    'maka_dari', 'adapun', 'akan', 'bahwa', 'bahwasanya', 'sebab', 'jika',
    'kalau', 'apabila', 'andai', 'andaikata', 'seandainya', 'seumpama',
    'seakan', 'seolah', 'ibarat', 'sebagaimana', 'seperti', 'bagai',
    'laksana', 'daripada', 'alih', 'daripada',
    'satu', 'dua', 'tiga', 'empat', 'lima', 'enam', 'tujuh', 'delapan',
    'sembilan', 'sepuluh', 'seratus', 'seribu', 'sejuta', 'pertama',
    'kedua', 'ketiga', 'keempat', 'kelima',
])

# Kata-kata untuk melengkapi judul yang terlalu pendek
RANDOM_WORDS = [
    'Video Sotwe', 'Video Wiki', 'Lagi Viral', 'Bokep Dood', 'Twitter', 'Bokepsatset', 
    'Simontok', 'Video Viral', 'Bokep Video', 'Video Yandex', 'Xpanas', 'Full Album', 
    'Doodstream', 'Bokepsin', 'Link Asupan', 'Bebasindo', 'Pekoblive', 'Terabox', 
    'Streaming', 'Videy Link Telegram', 'Tiktok', 'Telegram', 'Asupan Viral', 'Videos', 'Poophd', 
    'Video Yandex', 'Full Album', 'Bokepindo', 'Terupdate', 'Links Tele', 
    'Skandal Mesum', 'Dodstream', 'Link Pemersatu', 'Update', 'Dood Viral', 'Lulustream', 'Website', 
    'Doodsflix', 'Yakwad', 'Doodflix', 'Doodstreem', 'Asupan Viral', 
    'Pejuang Lendir', 'Popstream', 'Staklam', 'Bokepind', 'Video Bokep', 
    'Bokep31', 'Video Indo', 'Toketbagus', 'Doods Pro', 'Bokepin', 'DoodTele', 'Memeksiana'
]

# Kata-kata prioritas untuk penentuan kategori
PRIORITY_WORDS = [
    # Kategori umum viral
    'hijab', 'dodstream', 'Prank Ojol', 'simontok', 'terabox', 'lulustream', 'doodstream', 'prank ojol', 
    'chindo', 'adik kakak', 'tante yona', 'stw', 'trending', 'cewek colmek', 'remaja', 'pijat plus', 
    'mbah maryono', 'jav', 'jilbab', 'tobrut', 'skandal', 'tante yona', 'lokal', 'terbaru', 
    'hot', 'vcs', 'onlyfans', 'telegram', 'jepang', 'china', 'indonesia', 'malaysia', 
    'vietnam', 'barat', 'binor', 'bokep viral',
    'bokep pelajar',
    'video ngentot',
    'bokep perawan',
    'jilbab mesum',
    'prank ojol',
    'pijat plus',
    'sepong kontol',
    'hijab tobrut',
    'tante sange',
    'abg viral',
    'skandal mesum',
    'syakirah',
    'doggy style',
    'tante bohay',
    'cewek semok',
    'msbreewc',
    'cewek tobrut',
    'janda sange',
    'bokep jepang',
    'bokepsatset',
    'bebasindo',
    'doodstream',
    'doods pro',
    'dood tele',
    'cantik Tobrut',
    'memeksiana',
    'tante sange',
    'susu gede',
    'adik kakak',
    'simontok',
    'bokep indo',
    'bokep stw',
    'video lokal',
]
